# Generated by Django 5.1.6 on 2025-02-08 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dialogue", models.JSONField(verbose_name="对话数据")),
                ("behavior", models.JSONField(verbose_name="行为数据")),
                ("metadata", models.JSONField(verbose_name="元数据")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotated",
                    models.BooleanField(default=False, verbose_name="已标注"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务数据",
                "verbose_name_plural": "任务数据",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LinkScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_index", models.IntegerField(verbose_name="链接索引")),
                ("score", models.IntegerField(verbose_name="评分")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评分人员",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_scores",
                        to="myapp.taskdata",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "链接评分",
                "verbose_name_plural": "链接评分",
                "unique_together": {("task", "link_index", "annotator")},
            },
        ),
        migrations.CreateModel(
            name="DialogueAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dialogue_id", models.CharField(max_length=50, verbose_name="对话ID")),
                ("response_id", models.CharField(max_length=50, verbose_name="回复ID")),
                (
                    "quality_score",
                    models.IntegerField(
                        choices=[
                            (1, "1分 - 质量差"),
                            (2, "2分 - 质量一般"),
                            (3, "3分 - 质量良好"),
                            (4, "4分 - 质量优秀"),
                            (5, "5分 - 质量完美"),
                        ],
                        verbose_name="质量评分",
                    ),
                ),
                (
                    "annotation_comment",
                    models.TextField(blank=True, null=True, verbose_name="标注备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="标注人员",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="myapp.taskdata",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话标注",
                "verbose_name_plural": "对话标注",
                "unique_together": {
                    ("task", "dialogue_id", "response_id", "annotator")
                },
            },
        ),
    ]
