# Generated by Django 5.1.5 on 2025-02-25 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dialogueannotation",
            name="clarity",
            field=models.IntegerField(
                blank=True,
                choices=[(3, "非常清晰"), (2, "基本清晰"), (1, "不够清晰")],
                null=True,
                verbose_name="回答清晰度",
            ),
        ),
        migrations.AddField(
            model_name="dialogueannotation",
            name="completeness",
            field=models.IntegerField(
                blank=True,
                choices=[(3, "完整回答"), (2, "部分回答"), (1, "不完整回答")],
                null=True,
                verbose_name="回答完整性",
            ),
        ),
        migrations.AddField(
            model_name="dialogueannotation",
            name="improvement_suggestions",
            field=models.TextField(blank=True, null=True, verbose_name="改进建议"),
        ),
        migrations.AddField(
            model_name="dialogueannotation",
            name="question_type",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="问题类型"
            ),
        ),
        migrations.AddField(
            model_name="dialogueannotation",
            name="relevance_score",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (3, "3分 - 高度相关"),
                    (2, "2分 - 部分相关"),
                    (1, "1分 - 完全不相关"),
                ],
                null=True,
                verbose_name="相关性评分",
            ),
        ),
        migrations.AddField(
            model_name="dialogueannotation",
            name="required_elements",
            field=models.JSONField(blank=True, default=list, verbose_name="必要元素"),
        ),
        migrations.AddField(
            model_name="linkscore",
            name="link_url",
            field=models.URLField(default="", max_length=500, verbose_name="链接地址"),
        ),
        migrations.CreateModel(
            name="SessionEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "satisfaction",
                    models.IntegerField(
                        choices=[
                            (1, "1分"),
                            (2, "2分"),
                            (3, "3分"),
                            (4, "4分"),
                            (5, "5分"),
                        ],
                        verbose_name="整体满意度",
                    ),
                ),
                (
                    "ai_success_rate",
                    models.IntegerField(
                        choices=[
                            (1, "1分"),
                            (2, "2分"),
                            (3, "3分"),
                            (4, "4分"),
                            (5, "5分"),
                        ],
                        verbose_name="AI自评成功率",
                    ),
                ),
                (
                    "search_intent",
                    models.CharField(
                        choices=[
                            ("information", "信息查询"),
                            ("navigation", "导航指引"),
                            ("transaction", "交易相关"),
                            ("communication", "沟通交流"),
                            ("entertainment", "娱乐"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="搜索意图",
                    ),
                ),
                (
                    "dissatisfaction_reasons",
                    models.JSONField(default=list, verbose_name="不满原因"),
                ),
                (
                    "session_notes",
                    models.TextField(blank=True, verbose_name="会话备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="标注人员",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_evaluations",
                        to="myapp.taskdata",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "unique_together": {("task", "annotator")},
            },
        ),
    ]
