# Generated by Django 5.1.5 on 2025-02-25 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_dialogueannotation_clarity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="linkscore",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="linkscore",
            name="dialogue_index",
            field=models.IntegerField(default=2, verbose_name="对话轮数"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="linkscore",
            unique_together={("task", "dialogue_index", "link_index", "annotator")},
        ),
    ]
