# Generated by Django 5.1.5 on 2025-02-25 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_linkscore_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="linkscore",
            old_name="dialogue_index",
            new_name="query_id",
        ),
        migrations.AlterUniqueTogether(
            name="linkscore",
            unique_together={("task", "query_id", "link_index", "annotator")},
        ),
    ]
