# Generated by Django 5.1.5 on 2025-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_rename_dialogue_index_linkscore_query_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessionevaluation",
            options={"verbose_name": "会话评估", "verbose_name_plural": "会话评估"},
        ),
        migrations.RemoveField(
            model_name="dialogueannotation",
            name="annotation_comment",
        ),
        migrations.RemoveField(
            model_name="dialogueannotation",
            name="clarity",
        ),
        migrations.RemoveField(
            model_name="dialogueannotation",
            name="completeness",
        ),
        migrations.RemoveField(
            model_name="dialogueannotation",
            name="improvement_suggestions",
        ),
        migrations.RemoveField(
            model_name="dialogueannotation",
            name="quality_score",
        ),
        migrations.RemoveField(
            model_name="dialogueannotation",
            name="question_type",
        ),
        migrations.RemoveField(
            model_name="dialogueannotation",
            name="relevance_score",
        ),
        migrations.RemoveField(
            model_name="dialogueannotation",
            name="required_elements",
        ),
        migrations.RemoveField(
            model_name="sessionevaluation",
            name="ai_success_rate",
        ),
        migrations.RemoveField(
            model_name="sessionevaluation",
            name="dissatisfaction_reasons",
        ),
        migrations.RemoveField(
            model_name="sessionevaluation",
            name="satisfaction",
        ),
        migrations.RemoveField(
            model_name="sessionevaluation",
            name="search_intent",
        ),
        migrations.RemoveField(
            model_name="sessionevaluation",
            name="session_notes",
        ),
        migrations.AddField(
            model_name="dialogueannotation",
            name="annotation_data",
            field=models.JSONField(blank=True, default=dict, verbose_name="标注数据"),
        ),
        migrations.AddField(
            model_name="sessionevaluation",
            name="evaluation_data",
            field=models.JSONField(blank=True, default=dict, verbose_name="评估数据"),
        ),
    ]
