# Generated by Django 5.1.5 on 2025-02-25 13:29

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_sessionevaluation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialogueannotation",
            name="created_at",
            field=models.BigIntegerField(
                default=myapp.models.current_timestamp, verbose_name="创建时间戳"
            ),
        ),
        migrations.AlterField(
            model_name="linkscore",
            name="created_at",
            field=models.BigIntegerField(
                default=myapp.models.current_timestamp, verbose_name="创建时间戳"
            ),
        ),
        migrations.AlterField(
            model_name="sessionevaluation",
            name="created_at",
            field=models.BigIntegerField(
                default=myapp.models.current_timestamp, verbose_name="创建时间戳"
            ),
        ),
        migrations.AlterField(
            model_name="taskdata",
            name="created_at",
            field=models.BigIntegerField(
                default=myapp.models.current_timestamp, verbose_name="创建时间戳"
            ),
        ),
    ]
