# Generated by Django 5.1.3 on 2025-02-26 03:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_dialogueannotation_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DialogueAnnotation",
            new_name="QueryAnnotation",
        ),
        migrations.RenameModel(
            old_name="SessionEvaluation",
            new_name="SessionAnnotation",
        ),
    ]
